### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by loscrs** [BaltimoreChad/SecurityCenter#1]
script is designed to delete all "manageble" scan results for the user.  if run by admin all scan results will be deleted but if run by non-admin user only their results will be deleted. Suggest that you let users know

Thanks

**Comment by BaltimoreChad** [comment]
Unfortunately I do not log in here nearly enough as I should.  I will go ahead and comment this, thank you for bringing this to my attention.

I added #3 to the top warning about running as admin - hopefully didn't cause you too much harm.

**Comment by gnosisfarm** [comment]
Thanks for the tip, Loscrs and Chad. The script deletes all results that the user has access to depending on the Group the user is in and the Group all of the scan results were in.  In my example, all of my scan results were in the "Full Access" group and my user was in the Full Access Group. Luckily I control+c'd the script before it deleted all of the good scans at the top.  (I backed up my appliance before this to make sure I didnt lose everything)

We were using a tenable plugin on the forescout NAC which was kicking off thousands of scans because of a misconif. Thanks for this helpful script. It definitely saved me hours.
